name: CI

on:
  push:
    branches:
      - master

    tags:
      - v*

  pull_request:

jobs:
  build_and_test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          wget https://github.com/bazelbuild/bazel/releases/download/3.7.1/bazel_3.7.1-linux-x86_64.deb
          sudo dpkg -i bazel_3.7.1-linux-x86_64.deb
          sudo apt install pkg-config

      - name: Build and Test
        run: |
          bazel test --color=yes //... > >(tee -a /tmp/test.log) 2>&1

  cross-compile:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Log into GitHub Container Registry
        run: echo "${{ secrets.CR_PAT }}" | docker login https://docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Pull Docker
        run: |
          docker pull docker.pkg.github.com/mihaigalos/docker/avr-gcc

      - name: Cross Compile
        run: ./.github/workflows/cross_compile.sh {{ targets }}
        env:
          targets:
            - AVR/Encryption/
